### ISSUE TITLE
Problem with the SSL CA cert

### ISSUE THREAD

**Issue by AndrewBMartin** [JuliaWeb/HTTPClient.jl#18]
Following up on this issue in the AWS library: https://github.com/amitmurthy/AWS.jl/issues/33.

I made the recommended change, and now I get the following error:

Error executing request : Problem with the SSL CA cert (path? access rights?)
 in exec_as_multi at C:\Users\Andrew Martin\.julia\v0.3\HTTPClient\src\HTTPC.jl:
702
 in get at C:\Users\Andrew Martin\.julia\v0.3\HTTPClient\src\HTTPC.jl:371

**Comment by JohnHBrock** [comment]
@AndrewBMartin how did you resolve this?

**Comment by AndrewBMartin** [comment]
@JohnHBrock I actually didn't. I was able to hack around it by requesting everything I needed with a Python a script.

The reason I closed the issue is that I don't think it's a problem with HttpClient.jl. See this discussion: https://groups.google.com/forum/#!topic/julia-users/wAVko_CRfsk

**Comment by JohnHBrock** [comment]
I figured out why I was getting the error: I had a single process making thousands of simultaneous connections via @async, and each connection was creating a file handle to the cert. My system's max # of open files per process was set at 1024, so the connections after the first 1024 couldn't access the certificate.
